name: develop branch auto ci process script

on:
  push:
    branches: [ develop ]

jobs:
  deploy:
    name: deploy
    runs-on: ubuntu-latest

    steps:
      - name: excuting remote ssh commands
        uses: appleboy/ssh-action@v0.1.9
        with:
          host: ${{ secrets.REMOTE_IP }} 
          username: ${{ secrets.REMOTE_USER }} 
          key: ${{ secrets.REMOTE_PRIVATE_KEY }}
          port: ${{ secrets.REMOTE_SSH_PORT }}
          script: | # 실행될 스크립트
            sudo su
            cd /home/ubuntu/kookmin-feed
            source venv/bin/activate
            git checkout develop
            git pull
            pip install -r requirements.txt
            pm2 start main.py --name "kookmin-feed" --interpreter /home/ubuntu/kookmin-feed/venv/bin/python