name: main branch auto ci process script

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    name: deploy
    runs-on: ubuntu-latest

    steps:
      - name: excuting remote ssh commands
        uses: appleboy/ssh-action@v0.1.9
        with:
          host: ${{ secrets.REMOTE_IP }} 
          username: ${{ secrets.REMOTE_USER }} 
          key: ${{ secrets.REMOTE_PRIVATE_KEY }}
          port: ${{ secrets.REMOTE_SSH_PORT }}
          script: | # 실행될 스크립트
            cd /home/ubuntu/kookmin-feed
            source venv/bin/activate
            sudo git pull
            pip install -r requirements.txt
            pm2 restart kookmin-feed
